name: Laravel CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
    - uses: actions/checkout@v4
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Update Dependencies
      run: composer update
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php artisan test

  deploy:
    needs: laravel-tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Install PHP and Composer
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'


    # - name: Generate key
    #   run: php artisan key:generate --force

    - name: Set Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Setup FTP for cPanel
      uses: SamKirkland/FTP-Deploy-Action@v4.2.0
      with:
        server: ${{ secrets.CPANEL_SERVER }} # Adresse de votre serveur FTP
        username: ${{ secrets.CPANEL_USERNAME }} # Nom d'utilisateur FTP
        password: ${{ secrets.CPANEL_PASSWORD }} # Mot de passe FTP
        local-dir: ./ # Dossier local à déployer
        server-dir: / # Dossier sur le serveur cPanel où le site doit être déployé
        # method: ftp # Méthode de déploiement (ftp ou ftps)
        exclude: |
          .git*
          node_modules/
          vendor/
        method: ftp # Méthode de déploiement (ftp ou ftps)

    - name: Add SSH key
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.CPANEL_SSH_PRIVATE_KEY }}
    
    - name: Add server to known_hosts
      run: ssh-keyscan -H ${{ secrets.CPANEL_SERVER }} >> ~/.ssh/known_hosts

    - name: Install Composer Dependencies on cPanel
      run: ssh -o StrictHostKeyChecking=no -o IdentitiesOnly=yes ${{ secrets.CPANEL_USERNAME }}@${{ secrets.CPANEL_SERVER }} "cd /test.acd.bf && php composer.phar install --no-dev --prefer-dist"
      